# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='question_text',
            new_name='comment_text',
        ),
    ]
